# Generated by Django 3.2.9 on 2021-12-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211206_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='tractor',
            name='implement',
            field=models.CharField(choices=[('a', 'Hola'), ('b', 'Hello'), ('c', 'Bonjour'), ('d', 'Boas')], default='a', max_length=1),
        ),
    ]
